import { useState } from 'react';
import { CheckCircle2, CircleX, Play, RotateCcw, Route, Zap } from 'lucide-react';
import { batchSimulate, simulateRegex } from '../lib/api';
import type { Graph } from '../types';
export default function Simulation({ regex, graph }: { regex: string; graph: Graph }) {
  const [text,setText]=useState('abb'); const [res,setRes]=useState<any>(); const [batch,setBatch]=useState('abb\naabb\nab\nbabb'); const [batchRes,setBatchRes]=useState<any>(); const [busy,setBusy]=useState(false);
  const run=async()=>{setBusy(true);try{setRes(await simulateRegex(regex,text));}finally{setBusy(false)}};
  const runBatch=async()=>setBatchRes(await batchSimulate(regex,batch.split(/\r?\n/).filter(Boolean)));
  return <div className="simulation-layout"><section className="simulation-card"><div className="sim-head"><div><div className="card-kicker"><Route size={13}/> DFA SIMULATOR</div><h3>Does this string belong to the language?</h3><p>Run the minimized DFA one character at a time.</p></div><span className="machine-badge"><Zap size={13}/> q{graph.start} start</span></div><div className="sim-input-row"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void run()} placeholder="Type an input string, e.g. abb"/><button className="primary-button" onClick={()=>void run()} disabled={busy}><Play size={16}/>{busy?'Running':'Simulate'}</button><button className="icon-button" onClick={()=>{setText('');setRes(undefined)}} title="Reset"><RotateCcw size={16}/></button></div>{res&&<div className={`result-banner ${res.simulation.accepted?'accepted':'rejected'}`}>{res.simulation.accepted?<CheckCircle2/>:<CircleX/>}<div><strong>{res.simulation.accepted?'Accepted':'Rejected'}</strong><p>{res.simulation.reason}</p></div></div>}{res?.simulation?.trace?.length>0&&<div className="trace"><div className="trace-title">Execution trace</div>{res.simulation.trace.map((x:any,i:number)=><div className={`trace-row ${x.status==='accepted'?'trace-ok':''}`} key={i}><span>{i+1}</span><b>q{x.from}</b><i>{JSON.stringify(x.input)}</i><Arrow /> <b>{x.to===null?'∅':`q${x.to}`}</b><small>{x.status}</small></div>)}</div>}</section><section className="batch-card"><div className="card-kicker">BATCH TESTING</div><h3>Test several strings</h3><p>One string per line.</p><textarea value={batch} onChange={e=>setBatch(e.target.value)} /><button className="secondary-button" onClick={()=>void runBatch()}><Zap size={15}/> Run batch</button>{batchRes&&<div className="batch-results">{batchRes.results.map((x:any,i:number)=><div key={i}><code>{JSON.stringify(x.text)}</code><span className={x.accepted?'ok':'bad'}>{x.accepted?'Accepted':'Rejected'}</span></div>)}</div>}</section></div>;
}
function Arrow(){return <span className="trace-arrow">→</span>}
